
from .resolved_ckpt_loader import NODE_CLASS_MAPPINGS as CKPT_M, NODE_DISPLAY_NAME_MAPPINGS as CKPT_D
from .resolved_lora_loader import NODE_CLASS_MAPPINGS as LORA_M, NODE_DISPLAY_NAME_MAPPINGS as LORA_D
from .resolved_catalog import NODE_CLASS_MAPPINGS as CAT_M, NODE_DISPLAY_NAME_MAPPINGS as CAT_D

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(CKPT_M)
NODE_CLASS_MAPPINGS.update(LORA_M)
NODE_CLASS_MAPPINGS.update(CAT_M)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(CKPT_D)
NODE_DISPLAY_NAME_MAPPINGS.update(LORA_D)
NODE_DISPLAY_NAME_MAPPINGS.update(CAT_D)
